### LIST OF HOTELS AND ALL DETAILS
### scheme/domain/subdirectory
GET http://localhost:3004/hotels HTTP/1.1

### ALL DETAILS FOR ONE HOTEL BY ID (includes all rooms)
### scheme/domain/subdirectory/:id
GET http://localhost:3004/hotels/b12425d07fba7d45dd89711d HTTP/1.1

